-- GENERATED CREATE TABLE STATMENT FOR THE ENTITY Post
CREATE TABLE Post (
	id INT,
	title VARCHAR(255),
	PRIMARY KEY (id)
);
-- SELECTING ALL THE ATTRBUTES FROM THE ENTITY Post (NO REFERENCES)
SELECT id, title FROM Post;
-- SELECTING ALL THE ATTRBUTES FROM THE ENTITY Post (NO REFERENCES) WHERE THE PRIMARY KEY IS EQUAL TO SOMETHING
SELECT id, title FROM Post WHERE id = ?;

