-- GENERATED CREATE TABLE STATMENT FOR THE ENTITY User
CREATE TABLE User (
	id VARCHAR(255),
	name VARCHAR(255),
	email VARCHAR(255),
	username VARCHAR(255),
	password VARCHAR(255),
	PRIMARY KEY (id)
);
-- SELECTING ALL THE ATTRBUTES FROM THE ENTITY User (NO REFERENCES)
SELECT id, name, email, username, password FROM User;
-- SELECTING ALL THE ATTRBUTES FROM THE ENTITY User (NO REFERENCES) WHERE THE PRIMARY KEY IS EQUAL TO SOMETHING
SELECT id, name, email, username, password FROM User WHERE id = ?;
-- GENERATED CREATE TABLE STATMENT FOR THE ENTITY Product
CREATE TABLE Product (
	id VARCHAR(255),
	prod_name VARCHAR(255),
	price DOUBLE,
	description VARCHAR(255),
	category VARCHAR(255),
	brand VARCHAR(255),
	PRIMARY KEY (id),
	FOREIGN KEY (category) REFERENCES Category(id),
	FOREIGN KEY (brand) REFERENCES Brand(id)
);
-- SELECTING ALL THE ATTRBUTES FROM THE ENTITY Product (NO REFERENCES)
SELECT id, prod_name, price, description FROM Product;
-- SELECTING ALL THE ATTRBUTES FROM THE ENTITY Product (NO REFERENCES) WHERE THE PRIMARY KEY IS EQUAL TO SOMETHING
SELECT id, prod_name, price, description FROM Product WHERE id = ?;
-- GENERATED CREATE TABLE STATMENT FOR THE ENTITY Category
CREATE TABLE Category (
	id VARCHAR(255),
	cat_name VARCHAR(255),
	PRIMARY KEY (id)
);
-- SELECTING ALL THE ATTRBUTES FROM THE ENTITY Category (NO REFERENCES)
SELECT id, cat_name FROM Category;
-- SELECTING ALL THE ATTRBUTES FROM THE ENTITY Category (NO REFERENCES) WHERE THE PRIMARY KEY IS EQUAL TO SOMETHING
SELECT id, cat_name FROM Category WHERE id = ?;
-- GENERATED CREATE TABLE STATMENT FOR THE ENTITY Review
CREATE TABLE Review (
	id VARCHAR(255),
	text VARCHAR(255),
	vote INT,
	user VARCHAR(255),
	product VARCHAR(255),
	PRIMARY KEY (id),
	FOREIGN KEY (user) REFERENCES User(id),
	FOREIGN KEY (product) REFERENCES Product(id)
);
-- SELECTING ALL THE ATTRBUTES FROM THE ENTITY Review (NO REFERENCES)
SELECT id, text, vote FROM Review;
-- SELECTING ALL THE ATTRBUTES FROM THE ENTITY Review (NO REFERENCES) WHERE THE PRIMARY KEY IS EQUAL TO SOMETHING
SELECT id, text, vote FROM Review WHERE id = ?;
-- GENERATED CREATE TABLE STATMENT FOR THE ENTITY Brand
CREATE TABLE Brand (
	id VARCHAR(255),
	brand_name VARCHAR(255),
	PRIMARY KEY (id)
);
-- SELECTING ALL THE ATTRBUTES FROM THE ENTITY Brand (NO REFERENCES)
SELECT id, brand_name FROM Brand;
-- SELECTING ALL THE ATTRBUTES FROM THE ENTITY Brand (NO REFERENCES) WHERE THE PRIMARY KEY IS EQUAL TO SOMETHING
SELECT id, brand_name FROM Brand WHERE id = ?;
